# Generated by Django 2.1.7 on 2019-04-07 21:52

import Character_Builder.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilityName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AbilityScoreSet',
            fields=[
                ('abilityScoreSetID', models.AutoField(primary_key=True, serialize=False)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('characterID', models.AutoField(primary_key=True, serialize=False)),
                ('characterName', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('maxHP', models.IntegerField(default=6)),
                ('currentHP', models.IntegerField(default=6)),
                ('alignment', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=True)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('user', models.ForeignKey(blank=True, default=Character_Builder.models.defaultUser, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('characterID', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=255)),
                ('hitDice', models.CharField(max_length=255)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Character_Builder.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRace',
            fields=[
                ('raceID', models.AutoField(primary_key=True, serialize=False)),
                ('raceName', models.CharField(max_length=255)),
                ('speed', models.IntegerField()),
                ('size', models.CharField(max_length=255)),
                ('strengthBonus', models.IntegerField(default=0)),
                ('dexterityBonus', models.IntegerField(default=0)),
                ('constitutionBonus', models.IntegerField(default=0)),
                ('intelligenceBonus', models.IntegerField(default=0)),
                ('wisdomBonus', models.IntegerField(default=0)),
                ('charismaBonus', models.IntegerField(default=0)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Character_Builder.Character')),
            ],
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Character_Builder.Character'),
        ),
    ]
