# Generated by Django 2.1.7 on 2019-03-28 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Character_Builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilityscoreset',
            name='abilityScoreValue',
        ),
        migrations.RemoveField(
            model_name='abilityscoreset',
            name='abilityScores',
        ),
        migrations.RemoveField(
            model_name='characterrace',
            name='abilityScoreBonusSetID',
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='charismaBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='constitutionBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='dexterityBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='intelligenceBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='strengthBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='wisdomBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Character_Builder.Character'),
        ),
    ]
