# Generated by Django 2.1.7 on 2019-03-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character_Builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
