# Generated by Django 2.1.5 on 2019-04-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character_Builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
