# Generated by Django 2.1.7 on 2019-03-28 02:12

import Character_Builder.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Character_Builder', '0002_character_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilityscoreset',
            name='abilityScoreValue',
        ),
        migrations.RemoveField(
            model_name='abilityscoreset',
            name='abilityScores',
        ),
        migrations.RemoveField(
            model_name='characterrace',
            name='abilityScoreBonusSetID',
        ),
        migrations.RemoveField(
            model_name='characterrace',
            name='character',
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='abilityscoreset',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, default=Character_Builder.models.defaultRace, null=True, on_delete=django.db.models.deletion.CASCADE, to='Character_Builder.CharacterRace'),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='charismaBonus',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='constitutionBonus',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='dexterityBonus',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='intelligenceBonus',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='strengthBonus',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='characterrace',
            name='wisdomBonus',
            field=models.IntegerField(default=10),
        ),
    ]
