# Generated by Django 2.1.7 on 2019-04-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Character_Builder', '0002_auto_20190407_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='character',
        ),
    ]
