# Generated by Django 2.1.7 on 2019-04-08 01:44

import Character_Builder.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Character_Builder', '0002_character_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='characterClass',
            field=models.ForeignKey(blank=True, default=Character_Builder.models.defaultClass, null=True, on_delete=django.db.models.deletion.PROTECT, to='Character_Builder.CharacterClass'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, default=Character_Builder.models.defaultRace, null=True, on_delete=django.db.models.deletion.PROTECT, to='Character_Builder.CharacterRace'),
        ),
    ]
