# Generated by Django 2.1.7 on 2019-03-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character_Builder', '0003_auto_20190327_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterrace',
            name='charismaBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='constitutionBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='dexterityBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='intelligenceBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='strengthBonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='wisdomBonus',
            field=models.IntegerField(default=0),
        ),
    ]
