# Generated by Django 2.1.5 on 2019-04-06 21:08


import Inventory.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Character_Builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.ForeignKey(default=Inventory.models.defaultCharacter, on_delete=django.db.models.deletion.CASCADE, to='Character_Builder.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=True)),
                ('inventory', models.ForeignKey(default=Inventory.models.defaultInventory, on_delete=django.db.models.deletion.CASCADE, to='Inventory.Inventory')),
            ],
        ),
    ]
