# Generated by Django 2.1.7 on 2019-03-03 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Character_Builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignID', models.IntegerField(unique=True)),
                ('campaignName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignDMID', models.IntegerField(unique=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Campaign_Manager.Campaign')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Character_Builder.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyID', models.IntegerField(unique=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Campaign_Manager.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='PartyCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Character_Builder.Character')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campaign_Manager.Party')),
            ],
        ),
    ]
