# Generated by Django 2.1.7 on 2019-03-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partycharacter',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
