# Generated by Django 2.1.5 on 2019-03-27 03:10

import Campaign_Manager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Campaign_Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=Campaign_Manager.models.defaultUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaignID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campaign_Manager.Campaign')),
            ],
        ),
    ]
