# Generated by Django 2.1.7 on 2019-04-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(to='Campaign_Manager.Campaign'),
        ),
        migrations.AlterField(
            model_name='party',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='Campaign_Manager.Campaign'),
        ),
    ]
