# Generated by Django 2.1.5 on 2019-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(to='Character_Builder.Character'),
        ),
    ]
