# Generated by Django 2.1.5 on 2019-03-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_Manager', '0002_campaigncomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigncomment',
            old_name='campaignID',
            new_name='campaign',
        ),
    ]
