# Generated by Django 2.1.7 on 2019-04-07 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_Manager', '0002_auto_20190405_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partycharacter',
            name='party',
        ),
        migrations.AlterField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
