# Generated by Django 2.1.7 on 2019-04-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_Manager', '0003_auto_20190407_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(default='default_campaign.jpg', upload_to='campaign_pics'),
        ),
    ]
