# Generated by Django 2.1.5 on 2019-04-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_Manager', '0003_auto_20190327_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncomment',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
