# Generated by Django 2.1.7 on 2019-04-07 20:12

import Campaign_Manager.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_Manager', '0004_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndm',
            name='user',
            field=models.ForeignKey(default=Campaign_Manager.models.defaultUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
