# Generated by Django 2.1.7 on 2019-04-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_Manager', '0005_auto_20190407_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(to='Character_Builder.Character'),
        ),
    ]
